name: SamurayEnd

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установить Node.js (если проект на JS/TS)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Установить зависимости
      - name: Install dependencies
        run: npm install

      # 4. Собрать проект
      - name: Build project
        run: npm run build

      # 5. выгрузи папку dest
      - name: Upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # 6. деплой на GitHub Pages (для статики)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
